### ISSUE TITLE
Build error W10

### ISSUE THREAD

**Issue by carlosnewmusic** [assap-org/assap#39]
**Desktop (please complete the following information):**
 - OS: W10

[2019-04-15T15_05_40_996Z-debug.log](https://github.com/assap-org/assap/files/3080823/2019-04-15T15_05_40_996Z-debug.log)
[2019-04-15T15_07_07_751Z-debug.log](https://github.com/assap-org/assap/files/3080817/2019-04-15T15_07_07_751Z-debug.log)
[2019-04-15T15_09_00_465Z-debug.log](https://github.com/assap-org/assap/files/3080811/2019-04-15T15_09_00_465Z-debug.log)

PS C:\Users\Administrador\Downloads\repo1\assap> npm install

> wmi-client@0.2.0 install C:\Users\Administrador\Downloads\repo1\assap\node_modules\wmi-client
> node scripts/install.js

> electron-chromedriver@2.0.0 install C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron-chromedriver
> node ./download-chromedriver.js

successfully downloaded and extracted!

> yorkie@2.0.0 install C:\Users\Administrador\Downloads\repo1\assap\node_modules\yorkie
> node bin/install.js

setting up Git hooks
done

> @tensorflow/tfjs-node@0.1.21 install C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

* Downloading libtensorflow
[==============================] 9639164/bps 99% 0.0s
* Building TensorFlow Node.js bindings
C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node\scripts\install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

    at cp.exec (C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node\scripts\install.js:154:13)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.1.21 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.1.21 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2019-04-15T15_05_40_996Z-debug.log
PS C:\Users\Administrador\Downloads\repo1\assap> npm update
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> @tensorflow/tfjs-node@0.1.21 install C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

* Downloading libtensorflow
[==============================] 14994028/bps 98% 0.0s
* Building TensorFlow Node.js bindings
C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node\scripts\install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

    at cp.exec (C:\Users\Administrador\Downloads\repo1\assap\node_modules\@tensorflow\tfjs-node\scripts\install.js:154:13)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.1.21 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.1.21 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2019-04-15T15_07_07_751Z-debug.log
PS C:\Users\Administrador\Downloads\repo1\assap> npm run electron:serve

> assap@0.1.1 electron:serve C:\Users\Administrador\Downloads\repo1\assap
> vue-cli-service electron:serve

C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrador\Downloads\repo1\assap\node_modules\vue-cli-plugin-electron-builder\lib\testWithSpectron.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assap@0.1.1 electron:serve: `vue-cli-service electron:serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assap@0.1.1 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2019-04-15T15_07_51_349Z-debug.log
PS C:\Users\Administrador\Downloads\repo1\assap> npm run electron:build

> assap@0.1.1 electron:build C:\Users\Administrador\Downloads\repo1\assap
> vue-cli-service electron:build

C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (C:\Users\Administrador\Downloads\repo1\assap\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrador\Downloads\repo1\assap\node_modules\vue-cli-plugin-electron-builder\lib\testWithSpectron.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assap@0.1.1 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assap@0.1.1 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2019-04-15T15_09_00_465Z-debug.log

**Comment by nereasainzdelamaza** [comment]
Thanks for your interest in ASSAP.

We were unable to reproduce the issue on a Windows10 machine.
The dependecies version are:
```
node -v
v9.11.2

npm -v
5.6.0

node-gyp -v
v6.0.1
```

We strongly recommend to install Python 3 as in few weeks Python 2.7 will not be supported.

Please, let us know if the problem has been solved.

**Comment by carlosnewmusic** [comment]
ya no da error, siguiendo las instrucciones aunque os falta poner que hay que abrir una ventana de powershell con permisos de administrador al menos eso me a pedido a mi al instalar "npm install --global --production windows-build-tools"
